[package]
name = "mentees"
version = "0.1.0"
edition = "2021"
description = "CLI to manage mentees"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
cli-table = "0.4.9"
rusqlite = { version = "0.32.0", features = ["bundled"] }
