name: Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run test coverage
        run: |
          cargo tarpaulin --out Xml --verbose

      - name: List target directory contents
        run: ls -R target/tarpaulin

      - name: Show Cobertura coverage results
        run: |
          cat target/tarpaulin/cobertura.xml || echo "No coverage report found"
