name: Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml

      - name: Extract line coverage from Cobertura XML
        uses: Mudlet/xmlstarlet-action@master
        id: extract_coverage
        with:
          args: sel -t -v "/coverage/@line-rate" cobertura.xml

      - name: Check line coverage threshold
        run: |
          line_coverage="${{ steps.extract_coverage.outputs.xmlstarlet_result }}"
          
          # Convert to integer percentage (assuming line_coverage is a float like 0.85)
          line_coverage_percent=$(awk "BEGIN {print int($line_coverage * 100)}")
          echo "Line Coverage: ${line_coverage_percent}%"

          # Set the threshold for line coverage
          threshold=20

          # Compare the coverage with the threshold
          if [ "$line_coverage_percent" -lt "$threshold" ]; then
            echo "Line coverage is below the threshold of ${threshold}%!"
            exit 1
          else
            echo "Line coverage meets the threshold of ${threshold}%."
          fi
