name: Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run test coverage
        run: |
          cargo tarpaulin --out Xml --verbose || echo "Tarpaulin failed"

      - name: List target directory contents
        run: ls -R target

      # Display the coverage results (if coverage.xml exists)
      - name: Show coverage results
        if: success()
        run: |
          cat target/tarpaulin/coverage.xml || echo "No coverage report found"
