name: Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml

      - name: Install xmlstarlet
        run: apt-get install -y xmlstarlet

      - name: Check and enforce line coverage threshold
        run: |
          if [ -f cobertura.xml ]; then
            line_coverage=$(xmlstarlet sel -t -v "/coverage/@line-rate" cobertura.xml)
            # Convert line coverage to percentage
            line_coverage_percent=$(echo "$line_coverage * 100" | bc)
            echo "Line Coverage: ${line_coverage_percent}%"
            
            # Set the threshold for line coverage
            threshold=80
            
            # Compare the coverage with the threshold
            if (( $(echo "$line_coverage_percent < $threshold" | bc -l) )); then
              echo "Line coverage is below the threshold of ${threshold}%!"
              exit 1
            else
              echo "Line coverage meets the threshold of ${threshold}%."
            fi
          else
            echo "Cobertura XML file does not exist."
            exit 1
