name: Release CLI

on:
  push:
    tags:
      - "v*" 

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract version from tag
      id: version
      run: |
        # Extract version from the tag (e.g., v1.2.3 -> 1.2.3)
        TAG_VERSION="${GITHUB_REF#refs/tags/v}"
        echo "Version: $TAG_VERSION"
        echo "version=$TAG_VERSION" >> $GITHUB_ENV

    - name: Set up Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable

    - name: Update Cargo.toml version
      run: |
        sed -i "" "s/^version = \".*\"/version = \"${{ env.version }}\"/" Cargo.toml
        echo "Updated Cargo.toml to version ${{ env.version }}"

    - name: Update Cargo.lock
      run: cargo update -w 

    - name: Build CLI
      run: cargo build --release --target aarch64-apple-darwin

    - name: Create tarball
      run: |
        mkdir dist
        chmod +x target/aarch64-apple-darwin/release/mentees # do i need this?
        tar -czvf dist/mentees-macos.tar.gz -C target/aarch64-apple-darwin/release mentees

    - name: Calculate SHA256 checksum
      id: sha256
      run: |
        shasum -a 256 dist/mentees-macos.tar.gz > dist/sha256.txt
        echo "sha256=$(cut -d ' ' -f 1 dist/sha256.txt)" >> $GITHUB_ENV

    - name: Commit updated Cargo.toml to main
      run: |
        git fetch origin main
        git checkout main

        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # Merge the detached HEAD commit (if needed)
        git merge --ff-only $GITHUB_SHA || echo "Already up-to-date"

        # Stage and commit changes
        git add Cargo.toml Cargo.lock
        git commit -m "Update Cargo.toml and Cargo.lock to version ${{ env.version }}"

        # Push changes back to main
        git push origin main

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/mentees-macos.tar.gz
        body: |
          🚀 **New Release: ${{ github.ref_name }}**
          - **SHA256:** ${{ env.sha256 }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Homebrew Formula
      env:
        GIT_AUTH_TOKEN: ${{ secrets.HOMEBREW_WRITE_ACCESS }}
      run: |
        git clone https://x-access-token:$GIT_AUTH_TOKEN@github.com/d-pagey/homebrew-mentees.git
        cd homebrew-mentees

        # Update URL
        sed -i "" "s|url \".*\"|url \"https://github.com/d-pagey/mentee_cli/releases/download/v${{ env.version }}/mentees-macos.tar.gz\"|" mentees.rb

        # Update SHA256
        sed -i "" "s|sha256 \".*\"|sha256 \"${{ env.sha256 }}\"|" mentees.rb

        # Update Version
        sed -i "" "s|version \".*\"|version \"${{ env.version }}\"|" mentees.rb

        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add mentees.rb
        git commit -m "Update mentees to ${{ github.ref_name }}"
        git push
