name: Release CLI

on:
  push:
    tags:
      - "v*" 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract version from tag
      id: version
      run: |
        # Extract version from the tag (e.g., v1.2.3 -> 1.2.3)
        TAG_VERSION="${GITHUB_REF#refs/tags/v}"
        echo "Version: $TAG_VERSION"
        echo "::set-output name=version::$TAG_VERSION"

    - name: Update Cargo.toml version
      run: |
        TAG_VERSION="${GITHUB_REF#refs/tags/v}" # Strip the 'v' prefix
        sed -i "s/^version = \".*\"/version = \"$TAG_VERSION\"/" Cargo.toml
        echo "Updated Cargo.toml to version $TAG_VERSION"

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build CLI
      run: cargo build --release

    - name: Create tarball
      run: |
        mkdir dist
        tar -czvf dist/mentees-macos.tar.gz -C target/release mentees

    - name: Calculate SHA256 checksum
      id: sha256
      run: |
        sha256sum dist/mentees-macos.tar.gz > dist/sha256.txt
        echo "::set-output name=sha256::$(cut -d ' ' -f 1 dist/sha256.txt)"

    - name: Commit updated Cargo.toml to main
      run: |
        git fetch origin main
        git checkout main

        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # Merge the detached HEAD commit (if needed)
        git merge --ff-only $GITHUB_SHA || echo "Already up-to-date"

        # Stage and commit changes
        git add Cargo.toml
        git commit -m "Update Cargo.toml to version ${{ steps.version.outputs.version }}"

        # Push changes back to main
        git push origin main

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/mentees-macos.tar.gz
        body: |
          🚀 **New Release: ${{ github.ref_name }}**
          - **SHA256:** ${{ steps.sha256.outputs.sha256 }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Homebrew Formula
      run: |
        git clone https://github.com/your-username/homebrew-mentees.git
        cd homebrew-mentees
        sed -i "s|url \".*\"|url \"https://github.com/d-pagey/mentee_cli/releases/download/${{ github.ref_name }}/mentees-macos.tar.gz\"|" mentees.rb
        sed -i "s|sha256 \".*\"|sha256 \"${{ steps.sha256.outputs.sha256 }}\"|" mentees.rb
        git add mentees.rb
        git commit -m "Update mentees to ${{ github.ref_name }}"
        git push
